[package]
name = "riat"
description = "Halo: Combat Evolved Script Compiler"
version = "0.1.0"
authors = ["Snowy Mouse"]
license = "GPL-3.0-only"

[lib]
name = "riat"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
riat-definitions = { path = "../riat-definitions" }
encoding = "0.2"
