[package]
name = "riatc"
description = "C and C++ bindings for Rat in a Tube"
version = "0.1.0"
authors = ["Snowy Mouse"]
license = "GPL-3.0-only"

[dependencies]
riat = { path = "../riat" }

[lib]
name = "riatc"
crate-type = ["staticlib"] # static only because packaging is easier with it
